#!/bin/bash
# Builds a standalone Pharos.app at build/Pharos.app.
set -euo pipefail
cd "$(dirname "$0")/.."

swift build -c release

APP=build/Pharos.app
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp .build/release/Pharos "$APP/Contents/MacOS/Pharos"
cp Scripts/Info.plist "$APP/Contents/Info.plist"

# Compile the Icon Composer document (Assets/AppIcon.icon, generated by
# Scripts/make-assets.swift) into Assets.car — on macOS 26+ the system
# renders the icon's Liquid Glass appearance live, including the dark/clear/
# tinted variants — plus a fallback AppIcon.icns rendered from the layers.
if [[ -d Assets/AppIcon.icon ]]; then
    ICONBUILD=$(mktemp -d)
    xcrun actool Assets/AppIcon.icon --compile "$ICONBUILD" \
        --platform macosx --minimum-deployment-target 26.0 \
        --app-icon AppIcon --output-partial-info-plist "$ICONBUILD/partial.plist" \
        --output-format human-readable-text --errors > /dev/null
    cp "$ICONBUILD/Assets.car" "$APP/Contents/Resources/Assets.car"
    cp "$ICONBUILD/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
    rm -rf "$ICONBUILD"
    /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string AppIcon" "$APP/Contents/Info.plist"
    /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$APP/Contents/Info.plist"
fi

# With CODESIGN_IDENTITY set (e.g. "Developer ID Application"), produce a
# distributable, notarization-ready signature (hardened runtime + timestamp).
# Otherwise fall back to ad-hoc, which is fine locally — Pharos needs no
# TCC permissions at all.
if [[ -n "${CODESIGN_IDENTITY:-}" ]]; then
    codesign --force --options runtime --timestamp --sign "$CODESIGN_IDENTITY" "$APP"
else
    codesign --force --sign - "$APP"
fi

echo "Built $APP"
echo "Run:  open $APP"
